"""Reusable feature-engineering logic for the Module 1 Airflow DAG.

Keeping the *what* (feature logic) separate from the *when/how* (the DAG wiring)
makes the pipeline testable on its own:

    python -c "from feature_pipeline import build_features; build_features(...)"

The functions here mirror the transforms taught in notebook 01 and produce a
parquet file whose schema matches ``feast/feature_repo/features.py`` so that
``feast apply`` / ``feast materialize`` work unchanged.
"""

from __future__ import annotations

import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

# --- Paths shared with the containers (see docker-compose volumes) -----------
# Raw landing zone (named volume), and the writable Feast repo the DAG manages.
DATA_DIR = Path(os.environ.get("PIPELINE_DATA_DIR", "/opt/airflow/data"))
FEAST_REPO_DIR = Path(os.environ.get("FEAST_REPO_DIR", "/opt/airflow/feast_repo"))
FEAST_REPO_SRC = Path(os.environ.get("FEAST_REPO_SRC", "/opt/airflow/feature_repo_src"))

RAW_PATH = DATA_DIR / "titanic_raw.parquet"
FEATURES_PATH = FEAST_REPO_DIR / "data" / "titanic_features.parquet"


# ---------------------------------------------------------------------------
# 1. Extract
# ---------------------------------------------------------------------------
def extract() -> str:
    """Load the raw Titanic data, with an offline synthetic fallback.

    Returns the path to the raw parquet so downstream tasks can pick it up.
    """
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    try:
        import seaborn as sns

        df = sns.load_dataset("titanic")
        source = "seaborn"
    except Exception:  # offline / no network -> deterministic synthetic data
        rng = np.random.default_rng(42)
        n = 891
        df = pd.DataFrame(
            {
                "survived": rng.integers(0, 2, n),
                "pclass": rng.choice([1, 2, 3], n, p=[0.24, 0.21, 0.55]),
                "sex": rng.choice(["male", "female"], n, p=[0.65, 0.35]),
                "age": rng.normal(29, 14, n).clip(0.4, 80).round(1),
                "sibsp": rng.integers(0, 5, n),
                "parch": rng.integers(0, 4, n),
                "fare": rng.gamma(2.0, 16.0, n).round(2),
                "embark_town": rng.choice(
                    ["Southampton", "Cherbourg", "Queenstown"], n, p=[0.72, 0.19, 0.09]
                ),
            }
        )
        source = "synthetic"

    df.to_parquet(RAW_PATH, index=False)
    print(f"[extract] source={source} rows={len(df)} -> {RAW_PATH}")
    return str(RAW_PATH)


# ---------------------------------------------------------------------------
# 2. Prepare the Feast repo (config-per-environment)
# ---------------------------------------------------------------------------
def prepare_feast_repo() -> str:
    """Materialize a writable, container-targeted copy of the Feast repo.

    The notebook uses ``feast/feature_repo`` with ``localhost:6379``. Inside
    Docker, the online store is reachable as the ``redis`` service instead, so we
    render a fresh ``feature_store.yaml`` here pointing at the right host. This is
    the same "one definition, per-environment config" idea a feature store gives
    you in production.
    """
    (FEAST_REPO_DIR / "data").mkdir(parents=True, exist_ok=True)

    # Copy the feature definitions (read-only source -> writable repo).
    if FEAST_REPO_SRC.exists():
        shutil.copy(FEAST_REPO_SRC / "features.py", FEAST_REPO_DIR / "features.py")

    redis_host = os.environ.get("FEAST_REDIS_HOST", "redis")
    redis_port = os.environ.get("FEAST_REDIS_PORT", "6379")

    yaml_text = f"""# Auto-generated by the Airflow DAG for in-container execution.
project: module1_features
provider: local
registry: data/registry.db
online_store:
  type: redis
  connection_string: "{redis_host}:{redis_port}"
offline_store:
  type: file
entity_key_serialization_version: 3
"""
    (FEAST_REPO_DIR / "feature_store.yaml").write_text(yaml_text)
    print(f"[prepare] feast repo ready at {FEAST_REPO_DIR} (online={redis_host}:{redis_port})")
    return str(FEAST_REPO_DIR)


# ---------------------------------------------------------------------------
# 3. Transform (the actual feature engineering)
# ---------------------------------------------------------------------------
def build_features() -> str:
    """Engineer model-ready features and write them where Feast expects them.

    The output schema matches ``features.py``: passenger_id (entity),
    event_timestamp + created (Feast bookkeeping) and the feature columns.
    """
    df = pd.read_parquet(RAW_PATH)

    out = pd.DataFrame()
    # Entity key.
    out["passenger_id"] = np.arange(1, len(df) + 1, dtype="int64")

    # Etiqueta para entrenar (no es una feature de Feast; viaja en el parquet
    # para que la tarea train_model pueda construir el set de entrenamiento).
    if "survived" in df.columns:
        out["survived"] = df["survived"].fillna(0).astype("int64")
    else:
        out["survived"] = 0

    # Numeric features (impute age with the median; cap nothing else).
    out["age"] = df["age"].fillna(df["age"].median()).astype("float32")
    out["fare"] = df["fare"].fillna(df["fare"].median()).astype("float32")

    # Log transform for the heavy-tailed fare (see notebook 01).
    out["fare_log"] = np.log1p(out["fare"]).astype("float32")

    # Standardized age (z-score).
    age_mean, age_std = out["age"].mean(), out["age"].std(ddof=0) or 1.0
    out["age_scaled"] = ((out["age"] - age_mean) / age_std).astype("float32")

    # Derived count features.
    family = df["sibsp"].fillna(0) + df["parch"].fillna(0) + 1
    out["family_size"] = family.astype("int64")
    out["is_alone"] = (family == 1).astype("int64")

    # Categoricals kept as strings (Feast serves them as-is; encode at train time).
    out["pclass"] = df["pclass"].fillna(3).astype("int64")
    out["sex"] = df["sex"].fillna("unknown").astype(str)
    out["embark_town"] = df["embark_town"].fillna("unknown").astype(str)

    # Feast bookkeeping columns.
    now = datetime.now(timezone.utc)
    out["event_timestamp"] = pd.Timestamp(now)
    out["created"] = pd.Timestamp(now)

    FEATURES_PATH.parent.mkdir(parents=True, exist_ok=True)
    out.to_parquet(FEATURES_PATH, index=False)
    print(f"[transform] wrote {len(out)} rows, {out.shape[1]} cols -> {FEATURES_PATH}")
    return str(FEATURES_PATH)


# ---------------------------------------------------------------------------
# 4. Validate (a tiny data-quality gate)
# ---------------------------------------------------------------------------
def validate_features() -> dict:
    """Fail the DAG early if the feature table is malformed."""
    df = pd.read_parquet(FEATURES_PATH)

    expected = {
        "passenger_id", "age", "fare", "fare_log", "age_scaled",
        "family_size", "is_alone", "pclass", "sex", "embark_town",
        "event_timestamp", "created",
    }
    missing = expected - set(df.columns)
    assert not missing, f"missing columns: {missing}"
    assert len(df) > 0, "feature table is empty"
    assert df["passenger_id"].is_unique, "passenger_id must be unique"
    key_nulls = df[["passenger_id", "event_timestamp"]].isnull().any().any()
    assert not key_nulls, "null entity key or timestamp"

    report = {"rows": int(len(df)), "cols": int(df.shape[1])}
    print(f"[validate] OK {report}")
    return report


# ---------------------------------------------------------------------------
# 5. Train (cierra el ciclo: feature store -> training set -> modelo -> MLflow)
# ---------------------------------------------------------------------------
def train_model() -> dict:
    """Entrena un clasificador simple con las features materializadas y lo
    registra en MLflow.

    Aqui se cierra el ciclo del modulo: el mismo parquet que alimenta el offline
    store de Feast se usa para construir el training set, se entrena un modelo
    que predice ``survived``, se evalua y todo (parametros, metricas y el modelo)
    queda registrado en el servidor compartido de MLflow.
    """
    import mlflow
    import mlflow.sklearn
    from sklearn.compose import ColumnTransformer
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import accuracy_score, roc_auc_score
    from sklearn.model_selection import train_test_split
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import OneHotEncoder

    df = pd.read_parquet(FEATURES_PATH)

    target = "survived"
    numeric = ["age_scaled", "fare_log", "family_size", "is_alone", "pclass"]
    categorical = ["sex", "embark_town"]

    X = df[numeric + categorical].copy()
    y = df[target].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y if y.nunique() > 1 else None
    )

    pre = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
        ],
        remainder="passthrough",
    )
    model = Pipeline(
        steps=[
            ("pre", pre),
            ("clf", LogisticRegression(max_iter=1000)),
        ]
    )

    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = float(accuracy_score(y_test, preds))
    try:
        proba = model.predict_proba(X_test)[:, 1]
        auc = float(roc_auc_score(y_test, proba))
    except Exception:
        auc = float("nan")

    # Tracking compartido: MLFLOW_TRACKING_URI=http://mlflow:5000 (dentro de la red).
    tracking_uri = os.environ.get("MLFLOW_TRACKING_URI", "http://mlflow:5000")
    mlflow.set_tracking_uri(tracking_uri)
    mlflow.set_experiment("module1_feature_pipeline")

    with mlflow.start_run(run_name="airflow_train_model") as run:
        mlflow.log_param("model", "LogisticRegression")
        mlflow.log_param("n_features", X.shape[1])
        mlflow.log_param("n_train", int(len(X_train)))
        mlflow.log_param("n_test", int(len(X_test)))
        mlflow.log_metric("accuracy", acc)
        if auc == auc:  # not NaN
            mlflow.log_metric("roc_auc", auc)
        mlflow.sklearn.log_model(model, artifact_path="model")
        run_id = run.info.run_id

    report = {"accuracy": acc, "roc_auc": auc, "run_id": run_id, "tracking_uri": tracking_uri}
    print(f"[train] {report}")
    return report
